- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: yes
  tags: installation

- name: Install required system packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: latest
    update_cache: true
  tags: installation

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: installation

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
  tags: installation

- name: Update apt and install docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    update_cache: true
  tags: installation

- name: Add the user to the docker group
  user:
    name: '{{ item }}'
    groups: docker
    append: yes
  loop:
    - vagrant
    - ubuntu
  tags: installation

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  tags: always

- name: Create directory for docker compose
  file:
    path: ~/.docker/cli-plugins/
    recurse: true
    state: directory
  tags: installation
  
- name: Install docker-compose
  get_url:
    url : https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-linux-x86_64
    dest: ~/.docker/cli-plugins/docker-compose
    mode: '755'
  tags: installation
