---
# tasks file for roles/docker

- name: Installing Docker from Role
  include_tasks: install.yml
  when: destroy is undefined

- name: Provision containers
  include_tasks: provision.yml
  when: destroy is undefined
  
- name: Destroy containers
  include_tasks: destroy.yml
  when: destroy | default('no') | bool